// =========================================
// Idukki Static Susceptibility Dashboard
// =========================================

function updateTime() {
    const timeElement = document.getElementById("updateTime");
    if (!timeElement) return;

    const now = new Date();
    const hours = String(now.getHours()).padStart(2, "0");
    const minutes = String(now.getMinutes()).padStart(2, "0");

    timeElement.textContent = `${hours}:${minutes}`;
}

updateTime();
setInterval(updateTime, 30000);


// =========================================
// Reference prediction
// =========================================

const reference = {
    lat: 9.9189,
    lon: 77.1025,
    susceptibility: 0.49
};

function riskClass(value) {
    if (value < 0.25) return "LOW";
    if (value < 0.50) return "MODERATE";
    if (value < 0.75) return "HIGH";
    return "VERY HIGH";
}

function showReferencePrediction() {
    const score = document.getElementById("riskScore");
    const badge = document.getElementById("riskBadge");
    const coords = document.getElementById("selectedCoords");
    const region = document.getElementById("selectedRegion");
    const description = document.getElementById("scoreDescription");

    const percent = Math.round(reference.susceptibility * 100);

    if (score) score.textContent = `${percent}%`;
    if (badge) badge.textContent = riskClass(reference.susceptibility);
    if (coords) coords.textContent = `${reference.lat.toFixed(4)}°, ${reference.lon.toFixed(4)}°`;
    if (region) region.textContent = "Idukki reference point";
    if (description) {
        description.textContent =
            "RF class-1 probability at the reference location. This is a static susceptibility estimate, not a rainfall-triggered warning.";
    }
}

showReferencePrediction();


// =========================================
// Leaflet map
// =========================================

const mapElement = document.getElementById("riskMap");
const loadingElement = document.getElementById("mapLoading");
const resetButton = document.getElementById("resetMap");

let riskMap = null;
let susceptibilityLayer = null;
let studyBounds = null;

// Fallback bounds. The JSON generated by create_web_susceptibility_map.py
// will replace these with exact EPSG:4326 bounds.
const fallbackBounds = [
    [9.2708, 76.6277],
    [10.3513, 77.4039]
];

function setMapStatus(message, visible = true) {
    if (!loadingElement) return;
    loadingElement.textContent = message;
    loadingElement.style.display = visible ? "flex" : "none";
}

async function loadSusceptibilityMap() {
    if (!mapElement || typeof L === "undefined") {
        setMapStatus("Leaflet could not be loaded.", true);
        return;
    }

    riskMap = L.map(mapElement, {
        zoomControl: true,
        attributionControl: true,
        minZoom: 8,
        maxZoom: 14
    });

    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        maxZoom: 19,
        attribution: "© OpenStreetMap contributors"
    }).addTo(riskMap);

    try {
        const boundsResponse = await fetch("map_data/idukki_map_bounds.json", {
            cache: "no-store"
        });

        if (boundsResponse.ok) {
            const b = await boundsResponse.json();
            studyBounds = [
                [b.south, b.west],
                [b.north, b.east]
            ];
        } else {
            studyBounds = fallbackBounds;
        }
    } catch (error) {
        console.warn("Could not load map bounds JSON. Using fallback bounds.", error);
        studyBounds = fallbackBounds;
    }

    riskMap.fitBounds(studyBounds, { padding: [10, 10] });

    try {
        susceptibilityLayer = L.imageOverlay(
            "map_data/idukki_static_susceptibility.png",
            studyBounds,
            {
                opacity: 0.82,
                interactive: false
            }
        ).addTo(riskMap);

        susceptibilityLayer.once("load", () => {
            setMapStatus("", false);
        });

        susceptibilityLayer.once("error", () => {
            setMapStatus("Susceptibility image not found. Run the map conversion script first.", true);
        });
    } catch (error) {
        console.error(error);
        setMapStatus("Could not load susceptibility layer.", true);
    }

    // Map click currently selects a coordinate only.
    // Point-level raster lookup will be connected to the backend later.
    riskMap.on("click", (event) => {
        const lat = event.latlng.lat.toFixed(5);
        const lon = event.latlng.lng.toFixed(5);

        const coords = document.getElementById("selectedCoords");
        const region = document.getElementById("selectedRegion");
        const score = document.getElementById("riskScore");
        const badge = document.getElementById("riskBadge");
        const description = document.getElementById("scoreDescription");

        if (coords) coords.textContent = `${lat}°, ${lon}°`;
        if (region) region.textContent = "Selected map point";
        if (score) score.textContent = "--";
        if (badge) badge.textContent = "MAP POINT";
        if (description) {
            description.textContent =
                "The susceptibility layer is active. Point-level feature extraction will be connected to this click interaction in the next backend step.";
        }
    });

    setTimeout(() => riskMap.invalidateSize(), 150);
}

loadSusceptibilityMap();


// =========================================
// Reset map
// =========================================

if (resetButton) {
    resetButton.addEventListener("click", () => {
        if (riskMap && studyBounds) {
            riskMap.fitBounds(studyBounds, {
                padding: [10, 10],
                animate: true
            });
        }

        showReferencePrediction();
    });
}
